SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO AS R 
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS GROUP_R
ON R.FOOD_TYPE = GROUP_R.FOOD_TYPE AND R.FAVORITES = GROUP_R.FAVORITES
ORDER BY FOOD_TYPE DESC;