SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_OUTS AS OUTS
JOIN ANIMAL_INS AS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE LIKE 'Intact%' 
AND (
    SEX_UPON_OUTCOME LIKE 'Spayed%' 
    OR SEX_UPON_OUTCOME LIKE 'Neutered%'
)
ORDER BY OUTS.ANIMAL_ID;